import type { Metadata } from "next";

import "./globals.css";

import { ThemeProvider } from "./context/ThemeContext";
import { Navbar } from "./components/Navbar";
import Footer from "./components/Footer";
import { FOOTER_DATA } from "./constants/footer";

export const metadata: Metadata = {
  title: "Getsemani",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`bg-white transition-colors dark:bg-gray-900 dark:text-white`}
      >
        <ThemeProvider>
          <Navbar />
          <main>{children}</main>
          <Footer {...FOOTER_DATA} />
        </ThemeProvider>
      </body>
    </html>
  );
}
